#!/bin/bash
#
# ProcessMaker function

function warn(){
    echo -e '\e[31m'"$1"'\e[0m';}
function info(){
    echo -e '\e[36m'"$1"'\e[0m';}
function check_root(){
    # Vérification des privilèges root
    if [[ "$(id -u)" -ne 0 ]]; then
            warn "Ce script doit étre exécuté en tant que root" >&2
            exit 0
    else
            info "Privilège Root: OK"
    fi}
function compatible() {
    local version="$1"
    local -n versions_array="$2"
    [[ ${versions_array[*]} =~ ${version} ]]}
function check_distro(){
    # Vérifie si le fichier os-release existe
    if [ -f /etc/os-release ]; then
    # Source le fichier /etc/os-release pour obtenir les informations de la distribution
    source /etc/os-release
    # Vérifie si la distribution est basée sur Debian, Ubuntu, Alma Linux, Centos ou Rocky Linux
        if [[ "${ID}" =~ ^(debian|ubuntu|almalinux|centos|rocky|rhel)$ ]]; then
            if compatible "${VERSION_ID}" DEBIAN_VERSIONS || compatible "${VERSION_ID}" UBUNTU_VERSIONS || compatible "${VERSION_ID}" ALMA_VERSIONS || compatible "${VERSION_ID}" CENTOS_VERSIONS || compatible "${VERSION_ID}" ROCKY_VERSIONS || compatible "${VERSION_ID}" REDHAT_VERSIONS; then
                info "La version de votre systeme d'exploitation (${ID} ${VERSION_ID}) est compatible."
            else
                warn "La version de votre système d'exploitation (${ID} ${VERSION_ID}) n'est pas considérée comme compatible."
                warn "Voulez-vous toujours forcer l'installation ? Attention, si vous choisissez de forcer le script, c'est à vos risques et périls."
                info "Etes-vous sûr de vouloir continuer ? [yes/no]"
                read -r response
                case "$response" in
                    O|o)
                        info "Continuing..."
                        ;;
                    N|n)
                        info "Exiting..."
                        exit 1
                        ;;
                    *)
                        warn "Réponse non valide. Quitter..."
                        exit 1
                        ;;
                esac
            fi
        fi
    else
        warn "Il s'agit d'une autre distribution que Debian ou Ubuntu qui n'est pas compatible."
        exit 1
    fi}
function check_install(){
    # Vérifie si le répertoire existe
    if [ -d "$1" ]; then
        warn "Le site est déjà installé. Version ""$glpi_cli_version"
        info "Nouvelle version trouver : ProcessMaker version $NEW_VERSION"
        if [ "$glpi_cli_version" == "$NEW_VERSION" ]; then
            info "Vous avez déjà la dernière version de ProcessMaker. Mise à jour annuler"
            sleep 5
            exit 0;
        else
            info "Voulez-vous mettre à jour ProcessMaker (O/N): "
            read -r MaJ
            case "$MaJ" in
                "O" | "o")
                    update
                    exit 0;;
                "N" | "n")
                    info "Sortie du programme."
                    efface_script
                    exit 0;;
                *)
                    warn "Action non reconnue. Sortie du programme."
                    efface_script
                    exit 0;;
            esac
        fi
    else
        warn "Nouvelle installation de ProcessMaker"
        install
    fi}
function update_distro(){
    if [[ "${ID}" =~ ^(debian|ubuntu)$ ]]; then
        info "Recherche des mises à jour"
        apt-get update > /dev/null 2>&1
        info "Application des mises à jour"
        apt-get upgrade -y > /dev/null 2>&1
    elif [[ "${ID}" =~ ^(almalinux|centos|rocky|rhel)$ ]]; then
        info "Recherche des mises à jour"
        dnf update -y > /dev/null 2>&1
        info "Application des mises à jour"
        dnf upgrade -y > /dev/null 2>&1
    fi}
function network_info(){
    INTERFACE=$(ip route | awk 'NR==1 {print $5}')
    IPADRESS=$(ip addr show "$INTERFACE" | grep inet | awk '{ print $2; }' | sed 's/\/.*$//' | head -n 1)
    # HOST=$(hostname)}
function install_packages(){
    if [[ "${ID}" =~ ^(debian|ubuntu)$ ]]; then
        sleep 1
        info "Installation des extensions de php"
        apt install -y --no-install-recommends php-{mysql,mbstring,curl,gd,xml,intl,ldap,apcu,opcache,xmlrpc,zip,bz2} > /dev/null 2>&1
        info "Installation des service lamp..."
        apt-get install -y --no-install-recommends curl tar apache2 mariadb-server perl curl jq php > /dev/null 2>&1
        info "Activation de MariaDB"
        systemctl enable mariadb > /dev/null 2>&1
        info "Activation d'Apache"
        systemctl enable apache2 > /dev/null 2>&1
        info "Redémarage d'Apache"
        systemctl restart apache2 > /dev/null 2>&1
    elif [[ "${ID}" =~ ^(almalinux|centos|rocky|rhel)$ ]]; then
        sleep 1
        dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm > /dev/null 2>&1
        dnf module reset -y php nginx mariadb > /dev/null 2>&1
        dnf module install -y php:8.2 > /dev/null 2>&1
        dnf module install -y nginx:1.24 > /dev/null 2>&1
        dnf module install -y mariadb:10.11 > /dev/null 2>&1
        info "Activation des mises à jour automatique"
        dnf install dnf-automatic -y > /dev/null 2>&1
        sed -i 's/^\(;\?\)\(apply_updates =\).*/\2 yes/' /etc/dnf/automatic.conf
        sed -i 's/^\(;\?\)\(reboot =\).*/\2 when-needed/' /etc/dnf/automatic.conf
        sed -i 's/^\(;\?\)\(upgrade_type =\).*/\2 security/' /etc/dnf/automatic.conf
        mkdir /etc/systemd/system/dnf-automatic.timer.d
        echo "[Unit]" > /etc/systemd/system/dnf-automatic.timer.d/override.conf
        echo "Description=dnf-automatic timer" >> /etc/systemd/system/dnf-automatic.timer.d/override.conf
        echo "ConditionPathExists=!/run/ostree-booted" >> /etc/systemd/system/dnf-automatic.timer.d/override.conf
        echo "Wants=network-online.target" >> /etc/systemd/system/dnf-automatic.timer.d/override.conf
        echo "[Timer]" >> /etc/systemd/system/dnf-automatic.timer.d/override.conf
        echo "OnCalendar=*-*-* 6:00" >> /etc/systemd/system/dnf-automatic.timer.d/override.conf
        echo "RandomizedDelaySec=60m" >> /etc/systemd/system/dnf-automatic.timer.d/override.conf
        echo "Persistent=true" >> /etc/systemd/system/dnf-automatic.timer.d/override.conf
        systemctl enable --now dnf-automatic.timer > /dev/null 2>&1
        info "Installation des extensions de php"
        dnf install -y php-{mysqlnd,mbstring,curl,gd,xml,intl,ldap,apcu,opcache,zip,bz2} > /dev/null 2>&1
        info "Installation des service lamp..."
        dnf install -y crontabs logrotate cronie tar nginx mariadb-server perl curl jq php epel-release > /dev/null 2>&1
        sed -i 's/^\(;\?\)\(user =\).*/\2 nginx/' /etc/php-fpm.d/www.conf
        sed -i 's/^\(;\?\)\(group =\).*/\2 nginx/' /etc/php-fpm.d/www.conf
        info "Activation et démarrage de MariaDB, d'ENGINE X et de PHP-FPM"
        systemctl enable --now mariadb nginx php-fpm > /dev/null 2>&1
        firewall-cmd --permanent --zone=public --add-service=http > /dev/null 2>&1
        firewall-cmd --reload > /dev/null 2>&1
    fi }
function mariadb_configure(){
    info "Configuration de MariaDB"
    sleep 1
    systemctl start mariadb > /dev/null 2>&1
    (echo ""; echo "y"; echo "y"; echo "$SLQROOTPWD"; echo "$SLQROOTPWD"; echo "y"; echo "y"; echo "y"; echo "y") | mysql_secure_installation > /dev/null 2>&1
    sleep 1
    mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';" > /dev/null 2>&1
    # Create a new database
    mysql -e "CREATE DATABASE glpi;" > /dev/null 2>&1
    # Create a new user
    mysql -e "CREATE USER 'glpi_user'@'localhost' IDENTIFIED BY '$SQLPMPWD';" > /dev/null 2>&1
    # Grant privileges to the new user for the new database
    mysql -e "GRANT ALL PRIVILEGES ON glpi.* TO 'glpi_user'@'localhost';" > /dev/null 2>&1
    # Reload privileges
    mysql -e "FLUSH PRIVILEGES;" > /dev/null 2>&1
    # 
    mysql -e "GRANT SELECT ON mysql.time_zone_name TO 'glpi_user'@'localhost'" > /dev/null 2>&1
    # Initialize time zones datas
    info "Configuration de TimeZone"
    mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p"$SLQROOTPWD" mysql > /dev/null 2>&1
    echo "[mysqld]" > /etc/mysql/conf.d/my.cnf
    echo "back_log = 16000" >> /etc/mysql/conf.d/my.cnf
    echo "connect_timeout = 31536000" >> /etc/mysql/conf.d/my.cnf
    echo "explicit_defaults_for_timestamp = ON" >> /etc/mysql/conf.d/my.cnf
    echo "host_cache_size = 653" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_adaptive_hash_index = OFF" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_change_buffering = none" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_checksum_algorithm = none" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_checksums = OFF" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_doublewrite = OFF" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_flush_method = O_DIRECT" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_open_files = 6000" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_page_cleaners = 2" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_purge_batch_size = 600" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_purge_threads = 1" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_stats_persistent_sample_pages = 128" >> /etc/mysql/conf.d/my.cnf
    echo "innodb_use_native_aio = OFF" >> /etc/mysql/conf.d/my.cnf
    echo "interactive_timeout = 31536000" >> /etc/mysql/conf.d/my.cnf
    echo "max_allowed_packet = 1073741824" >> /etc/mysql/conf.d/my.cnf
    echo "max_connections = 1000" >> /etc/mysql/conf.d/my.cnf
    echo "max_execution_time = 18446744073709551615" >> /etc/mysql/conf.d/my.cnf
    echo "myisam_recover_options = OFF" >> /etc/mysql/conf.d/my.cnf
    echo "open_files_limit = 65535" >> /etc/mysql/conf.d/my.cnf
    echo "performance_schema = OFF" >> /etc/mysql/conf.d/my.cnf
    echo "query_cache_size = 464717824" >> /etc/mysql/conf.d/my.cnf
    echo "query_cache_type = ON" >> /etc/mysql/conf.d/my.cnf
    echo "skip_name_resolve = ON" >> /etc/mysql/conf.d/my.cnf
    echo "table_definition_cache = 20000" >> /etc/mysql/conf.d/my.cnf
    echo "table_open_cache_instances = 4" >> /etc/mysql/conf.d/my.cnf
    # Restart MariaDB
    systemctl restart mariadb
    sleep 1 }
function install_ps(){
    info "Téléchargement et installation de la version ${NEW_VERSION} de ProcessMaker..."
    # Get download link for the latest release
    DOWNLOADLINK=$(curl -s  https://api.github.com/repos/ProcessMaker/processmaker/releases/latest | jq -r '.assets[0].browser_download_url')
    wget -O /tmp/ps-latest.tgz "$DOWNLOADLINK" > /dev/null 2>&1
    tar xzf /tmp/ps-latest.tgz -C /opt/processmaker }
function setup_pm(){
    info "Configuration de ProcessMaker..."
    mkdir -p /var/log/processmaker
    elif [[ "${ID}" =~ ^(almalinux|centos|rocky|rhel)$ ]]; then
        chown -R nginx:nginx /var/log/processmaker
        chmod -R 777 /var/log/processmaker
        sleep 1
        # Add permissions
        chown -R nginx:nginx ${REP_PM}
        chmod -R 777 ${REP_PM}
        sleep 1
        cat > /etc/nginx/conf.d/pm.conf << EOF
server {
    listen 80;
    server_name glpi.localhost;
    root ${REP_PM}public;
    location / {
        try_files \$uri /index.php\$is_args\$args;
    }
    location ~ ^/index\.php$ {
        # the following line needs to be adapted, as it changes depending on OS distributions and PHP versions
        fastcgi_pass unix:/var/run/php-fpm/www.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    }
}
EOF
        cat > /etc/logrotate.d/glpi << EOF
# Rotate ProcessMaker logs daily, only if not empty
# Save 14 days old logs under compressed mode
/var/lib/glpi/files/_log/*.log {
    su nginx nginx
    daily
    rotate 14
    compress
    notifempty
    missingok
    create 644 nginx nginx
}
EOF
    chmod 0644 /etc/logrotate.d/glpi
    chown root:root /etc/logrotate.d/glpi
    chcon system_u:object_r:etc_t:s0 /etc/logrotate.d/glpi
    sed -i 's/^\(;\?\)\(session.cookie_httponly\).*/\2 = on/' /etc/php.ini > /dev/null 2>&1
    setsebool -P httpd_can_network_connect on
    setsebool -P httpd_can_network_connect_db on
    setsebool -P httpd_can_sendmail on
    semanage fcontext -a -t httpd_sys_rw_content_t "${REP_PM}(/.*)?" > /dev/null 2>&1
    semanage fcontext -a -t httpd_sys_rw_content_t "/var/lib/glpi(/.*)?" > /dev/null 2>&1
    semanage fcontext -a -t httpd_sys_rw_content_t "/var/log/processmaker(/.*)?" > /dev/null 2>&1
    semanage fcontext -a -t httpd_sys_rw_content_t "/etc/glpi(/.*)?" > /dev/null 2>&1
    semanage fcontext -a -t httpd_sys_rw_content_t "${REP_PM}marketplace" > /dev/null 2>&1
    restorecon -R ${REP_PM} > /dev/null 2>&1
    restorecon -R /var/lib/glpi > /dev/null 2>&1
    restorecon -R /var/log/processmaker > /dev/null 2>&1
    restorecon -R /etc/glpi > /dev/null 2>&1
    restorecon -R ${REP_PM}marketplace > /dev/null 2>&1
    # Restart de Nginx et php-fpm
    systemctl restart nginx php-fpm
   fi
    sleep 5
    rm -rf ${REP_PM}install/install.php
    sleep 5
    sed -i '$i \   public $date_default_timezone_set = ("'${TIMEZONE}'");' /etc/glpi/config/config_db.php
    # Change timezone and language
    mysql -e "INSERT INTO glpi.glpi_configs (context, name, value) VALUES ('core', 'timezone', '${TIMEZONE}');" > /dev/null 2>&1
    mysql -e "UPDATE glpi.glpi_configs SET value = "${LANG}" WHERE name = 'language';" > /dev/null 2>&1
    if [[ "${ID}" =~ ^(debian|ubuntu)$ ]]; then
        # Change permissions
        chown -Rc www-data:www-data /etc/glpi
        chmod -R 755 /etc/glpi
        chown -Rc www-data:www-data /var/log/processmaker
        chmod -R 755 /var/log/processmaker
        chown -Rc www-data:www-data ${REP_PM}
        chmod -R 755 ${REP_PM}
        systemctl restart apache2
        # Setup Cron task
        echo "*/2 * * * * www-data /usr/bin/php ${REP_PM}front/cron.php &>/dev/null" >> /etc/cron.d/glpi
    elif [[ "${ID}" =~ ^(almalinux|centos|rocky|rhel)$ ]]; then
         # Change permissions
        chown -R nginx:nginx /etc/glpi
        chmod -R 755 /etc/glpi
        chown -R nginx:nginx /var/log/processmaker
        chmod -R 755 /var/log/processmaker
        chown -R nginx:nginx ${REP_PM}
        chmod -R 755 ${REP_PM}
        systemctl restart nginx php-fpm
        echo "*/2 * * * * nginx /usr/bin/php ${REP_PM}front/cron.php &>/dev/null" >> /etc/cron.d/glpi
    fi }
function maj_user_pm(){
    info "Changement des mots de passe de ProcessMaker..."
    # Changer le mot de passe de l'admin glpi 
    mysql -u pm_user -p"${SQLPMPWD}" -e "USE pm; UPDATE pm_users SET password = MD5('${ADMINPMPWD}') WHERE name = 'glpi';"
function display_credentials(){
    info "<==========================> Détail de l'installation de ProcessMaker <=================================>"
    info "ProcessMaker Version: ${NEW_VERSION}"
    info "Répertoire d'installation de ProcessMaker: ${REP_PM}"
    warn "Il est important d'enregistrer ces informations. Si vous les perdez, elles seront irrécupérables."
    echo ""
    info "Les comptes utilisateurs par défaut sont :"
    info "UTILISATEUR  -  MOT DE PASSE       -  ACCES"
    info "glpi         -  ${ADMINPMPWD}       -  compte admin"
    echo ""
    info "Vous pouvez accéder à la page web de ProcessMaker à partir d'une adresse IP ou d'un nom d'hôte :"
    info "http://${IPADRESS}" 
    echo ""
    info "==> Database:"
    info "Mot de passe root: ${SLQROOTPWD}"
    info "Nom de la base de données ProcessMaker: glpi"
    info "<===============================================================================================>"
    echo ""
    info "Si vous rencontrez un problème avec ce script, veuillez le signaler sur GitHub : https://github.com/PapyPoc/glpi_install/issues"
}
function write_credentials(){
    cat <<EOF > /root/sauve_mdp.txt
<==========================> Détail de l'installation de ProcessMaker <=================================>
ProcessMaker Version: ${NEW_VERSION}
Répertoire d'installation de ProcessMaker: ${REP_PM}
Il est important d'enregistrer ces informations. Si vous les perdez, elles seront irrécupérables.

Les comptes utilisateurs par défaut sont :
UTILISATEUR       -  MOT DE PASSE       -  ACCES
info "glpi        -  ${ADMINPMPWD}       -  compte admin"
info "post-only   -  ${POSTPMPWD}       -  compte post-only"
info "tech        -  ${TECHPMPWD}       -  compte tech"
info "normal      -  ${NORMPMPWD}       -  compte normal"

Vous pouvez accéder à la page web de ProcessMaker à partir d'une adresse IP ou d'un nom d'hôte :
http://${IPADRESS}

==> Database:
Mot de passe root: ${SLQROOTPWD}
Nom de la base de données ProcessMaker: glpi
<===============================================================================================>

Si vous rencontrez un probléme avec ce script, veuillez le signaler sur GitHub : https://github.com/PapyPoc/glpi_install/issues
EOF
    chmod 700 /root/sauve_mdp.txt
    echo ""
    warn "Fichier de sauve_mdp.txt enregistrer dans /home"
    echo ""
}
function efface_script(){
    # Vérifie si le répertoire existe
    if [ -e "$REP_SCRIPT" ]; then
            warn "Le script est déjà présent."
            warn "Effacement en cours"
            rm -Rf "$REP_SCRIPT"
    fi
}
}
function maintenance(){
    if [ "$1" == "1" ]; then
        warn "Mode maintenance activer"
        if [[ "${ID}" =~ ^(debian|ubuntu)$ ]]; then
            sudo www-data php ${REP_PM}bin/console glpi:maintenance:enable  > /dev/null 2>&1
        elif [[ "${ID}" =~ ^(almalinux|centos|rocky|rhel)$ ]]; then
            sudo nginx php ${REP_PM}bin/console glpi:maintenance:enable  > /dev/null 2>&1
        fi
    elif [ "$1" == "0" ]; then
        info "Mode maintenance désactiver"
        if [[ "${ID}" =~ ^(debian|ubuntu)$ ]]; then
            sudo www-data php ${REP_PM}bin/console glpi:maintenance:disable  > /dev/null 2>&1
        elif [[ "${ID}" =~ ^(almalinux|centos|rocky|rhel)$ ]]; then
            sudo nginx php ${REP_PM}bin/console glpi:maintenance:disable  > /dev/null 2>&1
        fi
    fi
}
function backup_pm(){
        # Vérifie si le répertoire existe
        if [ ! -d "$REP_BACKUP" ]; then
            info "Création du  répertoire de sauvegarde avant mise à jour"
            mkdir "$REP_BACKUP"
        fi
        # Sauvergarde de la bdd
        info "Dump de la base de donnée"
        PASSWORD=$(sed -n 's/.*Mot de passe root: \([^ ]*\).*/\1/p' /root/sauve_mdp.txt)
        mysqldump -u root -p"$PASSWORD" --databases glpi > "${REP_BACKUP}${BDD_BACKUP}" > /dev/null 2>&1
        info "La base de donnée a été sauvergardé avec succè."
        # Sauvegarde des fichiers
        info "Sauvegarde des fichiers du sites"
        cp -Rf ${REP_PM} ${REP_BACKUP}backup_pm
        info "Les fichiers du site ProcessMaker ont été sauvegardés avec succès."
        info "Suppression des fichiers du site"
        rm -rf ${REP_PM}
}
function update_pm(){
        info "Remise en place des dossiers marketplace et plugins"
        cp -Rf ${REP_BACKUP}backup_pm/plugins ${REP_PM} > /dev/null 2>&1
        cp -Rf ${REP_BACKUP}backup_pm/marketplace ${REP_PM} > /dev/null 2>&1
        info "Mise à jour de la base de donnée du site"
        if [[ "${ID}" =~ ^(debian|ubuntu)$ ]]; then
            chown -R www-data:www-data ${REP_PM} > /dev/null 2>&1
            sudo www-data php ${REP_PM}bin/console db:update --quiet --no-interaction --force  > /dev/null 2>&1
        elif [[ "${ID}" =~ ^(almalinux|centos|rocky|rhel)$ ]]; then
            chown -R nginx:nginx ${REP_PM} > /dev/null 2>&1
            semanage fcontext -a -t httpd_sys_rw_content_t "${REP_PM}(/.*)?" > /dev/null 2>&1
            semanage fcontext -a -t httpd_sys_rw_content_t "${REP_PM}marketplace" > /dev/null 2>&1
            restorecon -Rv ${REP_PM} > /dev/null 2>&1
            restorecon -Rv ${REP_PM}marketplace > /dev/null 2>&1
            sudo nginx php ${REP_PM}bin/console db:update --quiet --no-interaction --force  > /dev/null 2>&1
        fi
        
        info "Nettoyage de la mise à jour"
        rm -rf ${REP_PM}install/install.php > /dev/null 2>&1
        rm -Rf "$REP_BACKUP"backup_pm > /dev/null 2>&1
}