#!/bin/bash
#
# ProcessMaker function

function compatible() {
    local version="$1"
    local -n versions_array="$2"
    [[ ${versions_array[*]} =~ ${version} ]]; }
# Fonction pour gérer les messages d'echo
log_and_display() {
    local message="$1"
    echo "$message" | echo "$(date '+%Y-%m-%d %H:%M:%S') $message" | tee -a "$SUCCESS_LOG"; }